title: Super Duper Oompa Loompa
description: Ommpa Loompa's Field manual.
baseurl: ""
url: "mykeybee.github.io"
repository: dinhanhthi/notetheme
paginate: 28

banner: "/assets/res/banner.png" # site banner (load when someone share your page url)
favicon: "/assets/res/favicon.png" # site's favicon (icon left side of your page)

# MatJek specific configurations
user: 
  name: "W.Wonka"
  email: "W.Wonka@superduperoompaloompa.co.uk"
  website: "superduperoompaloompa.co.uk"
  avatar: "/assets/res/user.png"
  github: "mykeybee"
google_tracking_id: ""
google_site_verification: ""
disqus_shortname: this-site

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title


gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

  future: true
